version: "3"

services:
   application:
        build: .
        restart: always
        ports:
            - 8080:8080
        container_name: app_test_h2_03
        environment:
            SPRING_DATASOURCE_URL: jdbc:h2:~/test;
            SPRING_DATASOURCE_USERNAME: sa
            SPRING_DATASOURCE_PASSWORD:
        networks:
            - custom_network

networks:
  custom_network: